baseURL: "https://haseebmajid.dev/"
title: Haseeb Majid
paginate: 25
theme: PaperModX

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: True
ignorefiles: ["source_code/.*"]

minify:
  disableXML: true
  minifyOutput: true

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: dracula
    lineNos: false
    noClasses: false

params:
  env: production
  title: Haseeb Majid
  description: "Haseeb Majid's blog"
  keywords: [Blog, Portfolio, PaperMod]
  author: Me
  images: ["cover.png"]
  DateFormat: "2006-01-02"
  defaultTheme: auto

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false
  SeriesOpen: false
  showLikes: false

  assets:
    favicon: "/favicon.ico"
    favicon16x16: "/favicon-16x16.png"
    favicon32x32: "/favicon-32x32.png"
    apple_touch_icon: "/apple-touch-icon.png"
    safari_pinned_tab: "/safari-pinned-tab.svg"
    disableHLJS: true

  label:
    text: "Haseeb Majid"
    icon: /apple-touch-icon.png
    iconHeight: 35

  profileMode:
    enabled: true
    title: Haseeb Majid
    subtitle: "Backend software engineer 💻 and village cricketer 🏏"
    imageUrl: "https://www.gravatar.com/avatar/7ddefc94d562a0b5896ef7f1b7c69e0e?s=250"
    imageWidth: 250
    imageHeight: 250
    imageTitle: A photo of Haseeb Majid
    buttons:
      - name: Posts
        url: posts
      - name: Archive
        url: archive
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my blog

  socialIcons:
    - name: gitlab
      url: "https://gitlab.com/hmajid2301"
    - name: github
      url: "https://github.com/hmajid2301"
    - name: linkedin
      url: "https://www.linkedin.com/in/haseeb-majid-ba0a5194/"

  cover:
    hidden: true
    hiddenInList: true
    hiddenInSingle: true

  editPost:
    URL: "https://gitlab.com/hmajid2301/blog/-/blob/main/content"
    appendFilePath: true

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

  goatcounter: "haseebmajid"

taxonomies:
  category: categories
  tag: tags
  series: series

menu:
  main:
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 10
    - identifier: talks
      name: Talks
      url: /talks/
      weight: 20
    - identifier: uses
      name: Uses
      url: /uses/
      weight: 40
    - identifier: stats
      name: Stats
      url: https://stats.haseebmajid.dev/
      params:
        external: true
      weight: 50

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5
