[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.105.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[functions]
directory = "functions"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.104.3"

[dev]
command = "hugo server -D --buildFuture -b http://localhost:8888"
targetPort = 1313

[context.dev.environment]
CONTEXT = "branch-deploy"
