version: "3"

tasks:
  start_docker:
    cmds:
      - docker compose up --build

  start_server:
    cmds:
      - hugo server -D --buildFuture

  new_post:
    cmds:
      - scripts/add "{{.CLI_ARGS}}"

  new_talk:
    cmds:
      - hugo new --kind talk-bundle talks/{{.TALK_NAME}}
    env:
      TALK_NAME: foo
