version: "3"

tasks:
  start_server:
    cmds:
      - hugo server -D --buildFuture

  new_post:
    cmds:
      - new_post "{{.CLI_ARGS}}"

  new_talk:
    cmds:
      - hugo new --kind talk-bundle talks/{{.TALK_NAME}}
    env:
      TALK_NAME: foo
